# Generated by Django 4.2 on 2023-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_on'], 'verbose_name': '租戶', 'verbose_name_plural': '租戶'},
        ),
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='加入日期'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='租戶名稱'),
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(verbose_name='正在試用'),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateTimeField(verbose_name='截止日期'),
        ),
    ]
