# Generated by Django 4.2 on 2023-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_client_options_alter_client_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': '網域', 'verbose_name_plural': '網域'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(verbose_name='網域'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(verbose_name='主要網域'),
        ),
    ]
