# Generated by Django 4.2 on 2023-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_domain_options_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(verbose_name='架構名稱'),
        ),
    ]
