# Generated by Django 4.1.7 on 2023-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_relationalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order_set', through='products.RelationalProduct', to='products.product'),
        ),
    ]
