# Generated by Django 4.2 on 2023-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=50, verbose_name='區'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最後修改時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=50, verbose_name='郵政編碼'),
        ),
    ]
