# Generated by Django 4.2 on 2023-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('已付款', '已付款'), ('未付款', '未付款'), ('付款失敗', '付款失敗'), ('等待裝運', '等待裝運'), ('運輸中', '運輸中'), ('訂單完成', '訂單完成'), ('取消', '取消')], default='未付款', max_length=100, verbose_name='Status'),
        ),
    ]
