# Generated by Django 4.1.7 on 2023-04-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='商品分類描述(英)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='商品分類名稱(英)'),
        ),
    ]
