# Generated by Django 4.2 on 2023-05-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0005_relationalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_en',
        ),
        migrations.AddField(
            model_name='product',
            name='date_Published',
            field=models.DateTimeField(auto_now=True, verbose_name='上架日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='商品庫存量'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Number',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_set', to='products.productcategory', verbose_name='商品類別'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建日期'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='暫無資料', max_length=500, verbose_name='商品介紹'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建日期'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, default='暫無資料', max_length=500, verbose_name='商品分類描述'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, default='暫無資料', max_length=500, verbose_name='圖片描述'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image_set', to='products.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='relationalproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='編號'),
        ),
    ]
