# Generated by Django 4.2 on 2023-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productcategory_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='商品編號'),
        ),
    ]
