# Generated by Django 4.2 on 2023-05-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_id_alter_product_product_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
