# Generated by Django 4.2 on 2023-05-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_Number'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
